### ISSUE TITLE
Ropsten Syncing

### ISSUE THREAD

**Issue by quantumproducer** [ethereum/ropsten#15] opened 2018-01-29 23:12 UTC
I followed the github's instructions of geth --testnet removedb

then ran

geth --rpc --rpcapi eth,net,web3,personal --testnet --syncmode "fast" console --cache=1024

then manually added the bootnodes according to the github

I still have 0 from admin.peers, 0 for eth.blockNumber and eth.syncing is false.

How do I sync? How long will this take? I hear from 1 person on the Stack Exchange that it can take a week (!)

**Comment by artvel** [comment] 2018-01-31 12:04
same issue here

**Comment by 5chdn** [comment] 2018-02-07 09:42
Duplicate of #13

**Closed** 2018-08-21 17:52 UTC
